"""LLM prompts for various extraction and generation tasks."""

from .resume_extraction import RESUME_EXTRACTION_PROMPT, RESUME_EXTRACTION_SYSTEM
from .job_extraction import JOB_EXTRACTION_PROMPT, JOB_EXTRACTION_SYSTEM
from .interview_generation import INTERVIEW_GENERATION_PROMPT, INTERVIEW_GENERATION_SYSTEM
from .coaching_generation import COACHING_GENERATION_PROMPT, COACHING_GENERATION_SYSTEM

__all__ = [
    "RESUME_EXTRACTION_PROMPT",
    "RESUME_EXTRACTION_SYSTEM",
    "JOB_EXTRACTION_PROMPT",
    "JOB_EXTRACTION_SYSTEM",
    "INTERVIEW_GENERATION_PROMPT",
    "INTERVIEW_GENERATION_SYSTEM",
    "COACHING_GENERATION_PROMPT",
    "COACHING_GENERATION_SYSTEM",
]
